---
- name: Install Docker
  become: true
  hosts: BotTelegram:YOLOv5
  tasks:
    - name: Update and install docker
      shell:  |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        
        sudo systemctl start docker
        sudo usermod -aG docker $USER
        sudo chmod 666 /var/run/docker.sock
        
    - name: Verify Docker installation
      shell: sudo docker run hello-world

- name: Attach the image BotTelegram to EC2
  become: true
  hosts: BotTelegram
  tasks:
    - name: Run BotTelegram Docker container
      shell:  |
        docker run -d --restart always -p 8443:8443 ygalidan/bottelegram

- name: Attach the image YOLOv5 to EC2
  become: true
  hosts: YOLOv5
  tasks:
    - name: Run YOLOv5 Docker container
      shell:  |
        docker run -d --restart always ygalidan/yolo5