name: Create infra on AWS

on:
  push:
    brances:
      - play

jobs:
  CreateInfra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id "${{secrets.AWS_ACCESS_KEY_ID}}"
          aws configure set aws_secret_access_key "${{secrets.AWS_SECRET_ACCESS_KEY}}"
        
      - name: Install TF
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
          terraform -v

      - name: Create infrastructure on AWS 
        run: |
          cd TF/
          terraform init
          terraform apply -var-file region_us-east-tfvars